on: pull_request
name: Test and build
jobs:
  admin-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build an test Admin FrontEnd
        run: |
          npm ci
          npm run build
          npm run coverage
          npm run lint
          npm run format:check